# Generated by Django 3.2.25 on 2025-06-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
    ]
