# Generated by Django 3.2.25 on 2025-06-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_person_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('participated', models.BooleanField(default=False)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.privilege')),
            ],
            options={
                'unique_together': {('person', 'month', 'year')},
            },
        ),
    ]
