# Generated by Django 5.2.3 on 2025-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meetingattendance_alter_report_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingattendance',
            name='person_virtual',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('zoom', 'Zoom')], max_length=10, verbose_name='Tipo de asistencia'),
        ),
    ]
