# Generated by Django 5.2.3 on 2025-06-20 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_meetingattendance_person_virtual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingattendance',
            options={'ordering': ['-meeting_date'], 'verbose_name': 'Asistencia a reunión', 'verbose_name_plural': 'Asistencias a reuniones'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Informe de servicio', 'verbose_name_plural': 'Informes de servicio'},
        ),
        migrations.RemoveField(
            model_name='meetingattendance',
            name='person_virtual',
        ),
        migrations.RemoveField(
            model_name='meetingattendance',
            name='total',
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='in_person',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistencia Presencial'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='virtual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistencia Zoom'),
        ),
    ]
