# Generated by Django 5.2.3 on 2025-06-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_meetingattendance_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingAttendance',
            new_name='PersonVirtual',
        ),
    ]
