# Generated by Django 5.2.3 on 2025-06-23 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_meetingattendance_personvirtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvirtual',
            name='in_person',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistencia Presencial'),
        ),
        migrations.AlterField(
            model_name='personvirtual',
            name='virtual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistencia Zoom'),
        ),
        migrations.AlterUniqueTogether(
            name='personvirtual',
            unique_together={('meeting_date',)},
        ),
    ]
