# Generated by Django 5.2.3 on 2025-06-23 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_personvirtual_in_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvirtual',
            name='in_person',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistencia Presencial'),
        ),
        migrations.AlterField(
            model_name='personvirtual',
            name='virtual',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistencia Zoom'),
        ),
    ]
