# Generated by Django 5.2.3 on 2025-07-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_personvirtual_in_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegePermanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='baptism',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de bautismo'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')], default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='hope',
            field=models.BooleanField(choices=[(True, 'Ungido'), (False, 'Muchedumbre')], default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='privilege_permanent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.privilegepermanent'),
        ),
    ]
