# Generated by Django 5.2.3 on 2025-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_privilegepermanent_person_baptism_person_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='privilege_permanent',
        ),
        migrations.AddField(
            model_name='person',
            name='privileges_permanent',
            field=models.ManyToManyField(blank=True, null=True, to='core.privilegepermanent'),
        ),
    ]
