# Generated by Django 5.2.3 on 2025-07-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_person_privilege_permanent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
