# Generated by Django 5.2.3 on 2025-08-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_report_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='person',
            name='contacts',
            field=models.JSONField(blank=True, null=True, verbose_name='Contactos'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='name',
            field=models.CharField(help_text='Publicador,Auxiliar,PR', max_length=100),
        ),
        migrations.AlterField(
            model_name='privilegepermanent',
            name='name',
            field=models.CharField(help_text='Misionero,Precursor Especial,Precursor Regular,Siervo Ministerial,Anciano', max_length=100),
        ),
    ]
