# Generated by Django 5.2.3 on 2025-08-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person_address_person_contacts_person_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Contactos'),
        ),
    ]
