# Generated by Django 5.2.3 on 2025-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_person_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
