# Generated by Django 5.2.3 on 2026-04-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_person_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='maternal_surname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='paternal_surname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
