# Generated by Django 5.2.3 on 2026-08-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_person_maternal_surname_person_paternal_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='Contactos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')], default=False, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hope',
            field=models.BooleanField(choices=[(True, 'Ungido'), (False, 'Muchedumbre')], default=False, verbose_name='Esperanza'),
        ),
        migrations.AlterField(
            model_name='person',
            name='maternal_surname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='person',
            name='paternal_surname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.privilege', verbose_name='Privilegio'),
        ),
        migrations.AlterField(
            model_name='person',
            name='privileges_permanent',
            field=models.ManyToManyField(blank=True, null=True, to='core.privilegepermanent', verbose_name='Privilegio permanente'),
        ),
    ]
