# Generated by Django 5.2.3 on 2026-04-01 04:03

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaActividades',
            fields=[
            ],
            options={
                'verbose_name': 'Generador de Guía',
                'verbose_name_plural': 'Generador de Guía',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
