# Generated by Django 5.2.3 on 2026-04-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiaactividades',
            options={'verbose_name': 'Vida y Ministerio Cristianos', 'verbose_name_plural': 'Vida y Ministerio Cristianos'},
        ),
    ]
